[package]
name = "sdfview"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0"

image = { version = "0.25", features = ["rayon"] }
glam = "0.29"
num = "0.4"

sdflib = {path="../sdflib"}
rayon = "1.10.0"